name: explorations-in-envy-free-allocations
channels:
  - conda-forge
  - defaults
  - http://conda.anaconda.org/gurobi
  - r
dependencies:
  - python
  - ipykernel
  - nb_conda
  - jupyter_contrib_nbextensions
  - numpy
  - pandas
  - scipy
  - seaborn
  - matplotlib
  - isort
  - yapf
  - nbdime
  - ipywidgets
  - amplpy
  - gurobi
  - plotly
  - basemap
  - ipympl
  - psutil
  - plotly-orca
  - pip
  - pip:
    - imgkit
    - coinor.grumpy
    - xdot==0.6