name: explorations-in-envy-free-allocations
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipykernel
  - nb_conda
  - jupyter_contrib_nbextensions
  - numpy
  - pandas
  - scipy
  - seaborn
  - matplotlib
  - isort
  - yapf
  - nbdime
  - pip
  - pip:
    - imgkit