#!/bin/sh
jupyter contrib nbextension install --user
jupyter contrib nbextension install table_beautifier --py --overwrite
jupyter contrib nbextension install init_cell --py --overwrite
jupyter contrib nbextension install spellchecker --py --overwrite
jupyter contrib nbextension install toggle_all_line_numbers --py --overwrite
jupyter contrib nbextension install hide_input --py --overwrite
jupyter contrib nbextension install livemdpreview --py --overwrite
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension enable --py table_beautifier/main
jupyter nbextension enable --py init_cell/main
jupyter nbextension enable --py spellchecker/main
jupyter nbextension enable --py toggle_all_line_numbers/main
jupyter nbextension enable --py hide_input/main
jupyter nbextension enable --py livemdpreview/livemdpreview
